### PR TITLE
Remove tag from server interface

### PR DESCRIPTION
**Pull request by shortstuffsushi**
@aaustin @derrickstaten @Sarkar @qinweigong

Title pretty much says it all. Tag isn't needed anymore, removing from server interface and response.

### CODE REVIEW

**Comment by derrickstaten** [comment]
what was tag before? so curious

**Comment by qinweigong** [comment]
:+1:

**Comment by shortstuffsushi** [comment]
@derrickstaten In the past, the request tag was being passed into all the method in order to be added to the response so it could fall through the big ol `if` tree to find the appropriate handling. This was no longer necessary with the callbacks branch. Could probably have been removed there, but I missed it and it was already a huge diff.

**Comment by shortstuffsushi** [comment]
@derrickstaten For reference, [this](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/3e045d90290c18ea2ca753d49ee6bfcf1acf0a4b/Branch-SDK/Branch-SDK/Branch.m#L1618)

**Comment by derrickstaten** [comment]
ah, cool. thanks.

**Pull request merged**
