### PR TITLE
Promo Arigato

### PR DESCRIPTION
**Pull request by shortstuffsushi**
@derrickstaten @dmitrig01 @aaustin @qinweigong 

Rename referral codes to promo codes, to better indicate the purpose they serve.

### CODE REVIEW

**Comment by dmitrig01** [comment]
I'm all for the rename, if we can keep the old methods around for a while

**Comment by qinweigong** [comment]
README needs update too.

**Comment by aaustin** [comment]
Can you add a todo in asana for Android? :+1:

**Comment by shortstuffsushi** [comment]
@aaustin task added. This PR is now awaiting a backend update.

**Comment by derrickstaten** [comment]
functions well for me

**Comment by derrickstaten** [comment]
:+1: pending tests passing

**Pull request merged**
