### PR TITLE
added app_id param to get requests

### PR DESCRIPTION
**Pull request by qinweigong**
@dmitrig01 @aaustin

### CODE REVIEW

**Comment by dmitrig01** [comment]
I can't actually speak to the functionality, but:

@aaustin - we need to include the app id on all requests going forward, so we know which shard to queries to. for now, we will send legacy requests to all three shards and see which one gives us back data.

**Comment by aaustin** [comment]
ok cool - that sounds really ugly

**Comment by aaustin** [comment]
:+1:

**Comment by dmitrig01** [comment]
yep see https://github.com/BranchMetrics/branch-backend/pull/688/files#diff-54ee6cd60658735b0afa26e8af585600R733

**Pull request merged**
