### PR TITLE
Callback immediately if initFailed

### PR DESCRIPTION
**Pull request by qinweigong**
@aaustin @shortstuffsushi

### CODE REVIEW

**Comment by aaustin** [comment]
can we move the if callback with main dispatch to a separate function? Just to save on lines of code and characters

**Comment by qinweigong** [comment]
Yes, wil do!

**Comment by qinweigong** [comment]
Actually, maybe not! 
Because callbacks are of different types, i can pass them to the separate function as an id, but in the function i lose the context and don't know how to cast it back, and can't just use an id to call.

Or is there a way?

**Comment by aaustin** [comment]
ahh yea that's a wrench in the spokes for sure - sorry for the wild goose chase

**Comment by aaustin** [comment]
Oops forgot to :+1:

**Pull request merged**
